# fly.toml app configuration file generated for jamsync on 2025-10-04T16:51:30-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jamsync'
primary_region = 'sjc'

[build]
  [build.args]
    VITE_SUPABASE_URL = "https://elikhejyygxjxqswnues.supabase.co"
    VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsaWtoZWp5eWd4anhxc3dudWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NTUzMjksImV4cCI6MjA3NTEzMTMyOX0.7a-gGdxANOc9MkNEknDr8V2ouhc59INSGCgqFdMWQEs"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
